const UserActionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    FORGOT_SUCCESS: 'FORGOT_SUCCESS',
    FORGOT_FAIL: 'FORGOT_FAIL',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAIL: 'UPDATE_PASSWORD_FAIL',
    BOOKING_SUCCESS: 'BOOKING_SUCCESS',
    BOOKING_FAIL: 'BOOKING_FAIL',
    GET_BOOKING_DATA_SUCCESS: 'GET_BOOKING_DATA_SUCCESS',
    GET_BOOKING_DATA_FAIL: 'GET_BOOKING_DATA_FAIL',

    //
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
    GOOGLE_LOGIN_FAIL: 'GOOGLE_LOGIN_FAIL',
    FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
    FACEBOOK_LOGIN_FAIL: 'FACEBOOK_LOGIN_FAIL',

};

export default UserActionTypes;
